version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - webnet

  app:
    image: 'libraryproject:latest'
    build: ./
    container_name: app
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: always
    networks:
      - webnet

networks:
  webnet:
    driver: bridge


